/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare function disposeOverlay(): void

export declare function flashClick(point: OverlayPoint): void

export declare function getOverlayState(): OverlayState

export declare function hideOverlay(): void

export declare function jumpCursor(point: OverlayPoint): void

export interface OverlayBounds {
  x: number
  y: number
  width: number
  height: number
}

export declare const enum OverlayLevel {
  Normal = 'Normal',
  Floating = 'Floating',
  TornOffMenu = 'TornOffMenu',
  ModalPanel = 'ModalPanel',
  MainMenu = 'MainMenu',
  Status = 'Status',
  PopUpMenu = 'PopUpMenu',
  ScreenSaver = 'ScreenSaver'
}

export interface OverlayPoint {
  x: number
  y: number
}

export interface OverlayState {
  hasWindow: boolean
  windowVisible: boolean
  cursorVisible: boolean
  debugBackdropVisible: boolean
  level: string
  bounds: OverlayBounds
  cursorPosition: OverlayPoint
}

export declare function setAttachedWindowId(windowId?: number | undefined | null): void

export declare function setCursorPressed(pressed: boolean): void

export declare function setCursorVisible(visible: boolean): void

export declare function setDebugBackdrop(visible: boolean, label?: string | undefined | null): void

export declare function setOverlayBounds(bounds: OverlayBounds): void

export declare function setOverlayLevel(level: OverlayLevel): void

export declare function showOverlay(bounds: OverlayBounds, level: OverlayLevel): void
