/* auto-generated by NAPI-RS */
/* eslint-disable */
/** List on-screen windows with their owning application name and bounds. */
export declare function listWindows(options?: ListWindowsOptions | undefined | null): Array<MacWindow>

export interface ListWindowsOptions {
  /** When true (default), only return windows currently visible on a display. */
  onScreenOnly?: boolean
  /** When true (default), exclude desktop wallpaper / icon elements. */
  excludeDesktopElements?: boolean
  /**
   * When true, also include windows on layers != 0 (menu bar, dock, etc.).
   * Default: false - most callers only care about normal app windows.
   */
  includeSystemChrome?: boolean
}

export interface MacWindow {
  /**
   * Stable per-session window id. Matches the trailing number in
   * Electron's `desktopCapturer` source id `window:<windowId>:<displayIndex>`.
   */
  windowId: number
  /** Owning process bundle/executable name, e.g. "Safari", "Code", "Workspace". */
  ownerName: string
  ownerPid: number
  /**
   * Window title. May be null when the app does not expose one or when the
   * caller lacks Screen Recording permission.
   */
  title?: string
  bounds: MacWindowBounds
  /**
   * Window server layer. 0 == normal app window. Non-zero usually means
   * menu bar, dock, status bar, or other system chrome.
   */
  layer: number
  /** Whether the window is currently visible on a display. */
  onScreen: boolean
}

export interface MacWindowBounds {
  x: number
  y: number
  width: number
  height: number
}
