/* auto-generated by NAPI-RS */
/* eslint-disable */
export interface FileDescriptorLimitResult {
  beforeSoft: number
  beforeHard: number
  afterSoft: number
  afterHard: number
  requestedSoft: number
}

export declare function raiseFileDescriptorLimit(targetSoft?: number | undefined | null): FileDescriptorLimitResult
