/* auto-generated by NAPI-RS */
/* eslint-disable */
export interface AccessibilityFrame {
  x: number
  y: number
  width: number
  height: number
}

export interface AccessibilitySize {
  width: number
  height: number
}

export interface AccessibilityStatus {
  /** True when the process appears in Accessibility with the toggle on. */
  trusted: boolean
}

export interface AccessibilityTreeNode {
  id: number
  parentId?: number
  depth: number
  role: string
  roleDescription?: string
  subrole?: string
  title?: string
  description?: string
  identifier?: string
  value?: string
  valueType?: string
  url?: string
  help?: string
  enabled?: boolean
  selected?: boolean
  expanded?: boolean
  settable?: boolean
  position?: Point
  size?: AccessibilitySize
  frame?: AccessibilityFrame
  availableAttributes: Array<string>
  availableActions: Array<string>
  focused: boolean
}

/**
 * Activate a running app by pid. Used as a last-resort frontmost restoration
 * guard if a target app activates itself after receiving background input.
 */
export declare function activateApp(pid: number): boolean

/**
 * Perform an accessibility action on a node from the target app's focused-window AX tree.
 *
 * Node ids follow the same preorder traversal numbering used by
 * `get_focused_window_accessibility_tree`.
 */
export declare function axPressNode(options: AxPressNodeOptions): AxPressNodeResult

export interface AxPressNodeOptions {
  /** Target application pid. */
  pid: number
  /** Node id from the focused-window accessibility tree traversal. */
  nodeId: number
  /** Accessibility action name. Defaults to `AXPress`. */
  action?: string
  /** Traversal scope used to resolve `node_id`. Defaults to `focusedWindow`. */
  scope?: string
  /** Tree mode used to resolve `node_id`. Defaults to `interactive`. */
  mode?: string
  /** Maximum traversal depth used to resolve `node_id`. */
  maxDepth?: number
  /** Maximum emitted nodes used to resolve `node_id`. */
  maxNodes?: number
}

export interface AxPressNodeResult {
  pid: number
  nodeId: number
  action: string
  role: string
  title?: string
  identifier?: string
  description?: string
}

/**
 * Click into a specific window owned by `pid` **without activating its app**.
 *
 * Uses the `CGEventPostToPid` + per-window-id field pattern documented in
 * the bgclick-rev skill. Concretely, for each down/up event we:
 *
 * 1. Build an `NSEvent.mouseEvent(...)` at the screen-space point, then
 *    extract its `CGEvent`.
 * 2. Set `kCGMouseEventButtonNumber (3)` and `kCGMouseEventClickState (1)`.
 * 3. Set `kCGMouseEventSubtype (7) = 3` — the non-public "synthesized window
 *    targeted" subtype that some apps gate on.
 * 4. Set `kCGMouseEventWindowUnderMousePointer (91)` and field `92` to the
 *    target `CGWindowID` so the WindowServer routes the event to that window.
 * 5. Call private `CGEventSetWindowLocation` (resolved via `dlsym`) with the
 *    window-local point (`screenPoint - windowOrigin`).
 * 6. Keep modifier flags exactly as requested by the caller; production clicks
 *    do not add Command/Option as a delivery bypass.
 * 7. Post via `CGEventPostToPid(pid, event)`.
 *
 * The clicker app stays frontmost. The target window receives the click, and
 * its `NSWindow` becomes key (`NSWindowDidBecomeKeyNotification`), but
 * `NSApp.isActive` stays false on the target.
 */
export declare function backgroundClick(options: BackgroundClickOptions): void

export interface BackgroundClickOptions {
  /** Target process pid (e.g. `MacWindow.ownerPid` from @pichu/mac-window-list). */
  pid: number
  /** CoreGraphics window id of the target window (`MacWindow.windowId`). */
  windowId: number
  /**
   * Window outer bounds origin in CG global points. Used to compute the
   * window-local point that the private `CGEventSetWindowLocation` setter expects.
   */
  windowOriginX: number
  windowOriginY: number
  /** Click position in CG global points (top-left origin of the primary display). */
  x: number
  y: number
  button?: MouseButton
  /** 1 = single, 2 = double, 3 = triple. Defaults to 1. */
  count?: number
  /**
   * Optional modifier keys. NOTE: when `target_is_active` is false (or unset),
   * the implementation can OR in a synthetic modifier regardless — this is
   * the WindowServer "deliver to backgrounded app" filter bypass. The target
   * app will see that modifier in `modifierFlags`. This is a known trade-off.
   */
  modifiers?: ModifierFlags
  /**
   * Legacy escape hatch for synthetic modifier delivery bypass. Defaults to
   * false so production clicks are plain mouse events.
   */
  useCommandDeliveryBypass?: boolean
  /**
   * Which synthetic modifier to OR into background-delivery events if the
   * legacy bypass is explicitly enabled.
   */
  deliveryBypassModifier?: DeliveryBypassModifier
  /**
   * True if the target app is currently the foreground app. When false (the
   * default), the delivery bypass is applied so the WindowServer
   * actually delivers the event. When true, no bypass is needed and the
   * click registers without spurious modifiers.
   */
  targetIsActive?: boolean
  /** Milliseconds to hold between mouse down and up. Defaults to 0. */
  holdMs?: number
}

/**
 * Drag inside a specific window owned by `pid` **without activating its app**.
 *
 * Same per-event window-id-tagging pattern as `background_click`, applied to
 * every event in the drag sequence: down → N drag → up. All events go to the
 * same target window via `CGEventPostToPid`.
 */
export declare function backgroundDrag(options: BackgroundDragOptions): void

export interface BackgroundDragOptions {
  pid: number
  windowId: number
  windowOriginX: number
  windowOriginY: number
  fromX: number
  fromY: number
  toX: number
  toY: number
  button?: MouseButton
  /** Number of intermediate `mouseDragged` events. Defaults to 20. */
  steps?: number
  /** Total drag duration in ms. Defaults to 250. */
  durationMs?: number
  modifiers?: ModifierFlags
  /**
   * True if the target app is currently the foreground app. Used for
   * diagnostics; drag no longer adds a synthetic Command bypass.
   */
  targetIsActive?: boolean
}

/**
 * Press a single named key (with optional modifiers) targeting a specific
 * process. Same two-step model as `background_type`:
 *   1. If `window_id` is provided, AX-raise that window inside the target
 *      app so the key event lands in the right key window.
 *   2. Post the keyboard event via `CGEventPostToPid` — bypasses the system
 *      event tap and the foreground app entirely.
 */
export declare function backgroundPressKey(options: BackgroundPressKeyOptions): BackgroundPressKeyResult

export interface BackgroundPressKeyOptions {
  pid: number
  /** Target CGWindowID. STRONGLY recommended — see `BackgroundTypeOptions.window_id`. */
  windowId?: number
  key: string
  modifiers?: ModifierFlags
}

export interface BackgroundPressKeyResult {
  windowFocused: boolean
}

/**
 * Type Unicode text into a specific app's focused field WITHOUT activating
 * the app. Two-step process:
 *   1. If `window_id` is provided, call the AX `AXRaise` action on that
 *      window so it becomes the key window inside its own app — this does
 *      NOT activate the app at the system level, but it does ensure the
 *      next keystroke lands in *that* window's focused first responder.
 *   2. Build keyboard events with `CGEventKeyboardSetUnicodeString` and
 *      post them via `CGEventPostToPid(pid, event)` — events go directly
 *      to the target process's event queue, bypassing the system event
 *      tap and the foreground app entirely.
 */
export declare function backgroundType(options: BackgroundTypeOptions): BackgroundTypeResult

export interface BackgroundTypeOptions {
  /** Target process pid (e.g. `MacWindow.ownerPid`). */
  pid: number
  /**
   * Target CGWindowID. STRONGLY recommended. When provided the
   * implementation calls `ensure_window_key(pid, windowId)` via the AX API
   * before posting any keystrokes — this makes the matching window the key
   * window of the target app *without* activating the app, so the
   * keystrokes land in the focused first responder of the intended window
   * instead of getting silently dropped or routed to whatever window in the
   * target app happened to be key last.
   */
  windowId?: number
  text: string
  perCharDelayMs?: number
}

export interface BackgroundTypeResult {
  /**
   * True when the AX `AXRaise` action successfully focused `window_id`
   * inside the target app. False if no `window_id` was provided, the
   * window could not be matched, or the AX call failed (in which case
   * the keystrokes are still posted — they just may not land where you
   * expect).
   */
  windowFocused: boolean
  charactersPosted: number
}

export declare function captureDisplayPng(options: CaptureDisplayPngOptions): void

export interface CaptureDisplayPngOptions {
  /** CoreGraphics display id. Defaults to the main display when omitted. */
  displayId?: number
  /** Absolute output path for the PNG file. */
  path: string
}

export declare function captureWindowPng(options: CaptureWindowPngOptions): void

export interface CaptureWindowPngOptions {
  /** CoreGraphics window id to capture. */
  windowId: number
  /** Absolute output path for the PNG file. */
  path: string
}

/**
 * Returns whether the current process is trusted for Accessibility. This is
 * required for the WindowServer to deliver synthetic events to other apps.
 */
export declare function checkAccessibility(): AccessibilityStatus

export declare const enum DeliveryBypassModifier {
  Command = 'Command',
  Option = 'Option'
}

/**
 * Standalone helper: make `window_id` the key window of `pid`'s app via the
 * AX `AXRaise` action — without activating the app. Returns true on success.
 * Useful when an agent has already issued one keyboard call and wants to
 * re-focus a different window before the next one.
 */
export declare function ensureAppWindowKey(pid: number, windowId: number): boolean

export interface FocusedWindowAccessibilityTree {
  pid: number
  windowTitle?: string
  mode: string
  focusedElementId?: number
  nodeCount: number
  truncated: boolean
  text: string
  nodes: Array<AccessibilityTreeNode>
}

export interface FocusedWindowAccessibilityTreeOptions {
  /** Target application pid. */
  pid: number
  /** Traversal scope. Defaults to `focusedWindow`; `app` starts at the app AX root. */
  scope?: string
  /** Output mode. Defaults to `interactive`; `raw` emits every traversed AX element. */
  mode?: string
  /** Maximum traversal depth starting from the focused window root. */
  maxDepth?: number
  /** Maximum number of nodes to collect before truncating. */
  maxNodes?: number
}

export interface FrontmostApp {
  /**
   * Pid of the current frontmost (foreground) app, or null if it could not
   * be determined (e.g. workspace not yet initialized).
   */
  pid?: number
}

/**
 * Dump the macOS Accessibility tree for the target app's focused window.
 *
 * The output is capped by `max_depth` and `max_nodes` to avoid pathological
 * trees from WebViews / complex Electron apps.
 */
export declare function getFocusedWindowAccessibilityTree(options: FocusedWindowAccessibilityTreeOptions): FocusedWindowAccessibilityTree

/** Return the pid of the current foreground app via NSWorkspace. */
export declare function getFrontmostAppPid(): FrontmostApp

/** True when the given pid is the foreground app. */
export declare function isAppActive(pid: number): boolean

export interface ModifierFlags {
  shift?: boolean
  control?: boolean
  /** macOS Option / Alt key. */
  option?: boolean
  command?: boolean
  /** macOS function (Fn) key. */
  function?: boolean
}

export declare const enum MouseButton {
  Left = 'Left',
  Right = 'Right',
  Middle = 'Middle'
}

/**
 * Click at the given global point. Always issues a move event first so apps
 * see the cursor enter the target before the click. `count` controls
 * single/double/triple click semantics via the `kCGMouseEventClickState`
 * field — required for double-click to actually register as a double-click.
 */
export declare function mouseClick(options: MouseClickOptions): void

export interface MouseClickOptions {
  x: number
  y: number
  /** Defaults to "left". */
  button?: MouseButton
  /** 1 = single click, 2 = double, 3 = triple. Defaults to 1. */
  count?: number
  /** Optional modifier flags held during the click. */
  modifiers?: ModifierFlags
  /**
   * Milliseconds to hold the button between down and up. Defaults to 0
   * (immediate). Useful for "long press" or when the target needs time to
   * register a press.
   */
  holdMs?: number
}

/**
 * Drag from one point to another with intermediate `mouseDragged` events.
 * Useful for selecting text, moving windows, sliders, file drag-and-drop.
 */
export declare function mouseDrag(options: MouseDragOptions): void

export interface MouseDragOptions {
  fromX: number
  fromY: number
  toX: number
  toY: number
  /** Defaults to "left". */
  button?: MouseButton
  /** Number of intermediate mouse-dragged events. More = smoother. Defaults to 20. */
  steps?: number
  /** Total drag duration in milliseconds. Defaults to 250. */
  durationMs?: number
}

/**
 * Move the cursor to the given global point. Posts a `mouseMoved` event so
 * hover-aware UI updates correctly.
 */
export declare function mouseMove(options: MouseMoveOptions): void

export interface MouseMoveOptions {
  x: number
  y: number
}

export interface Point {
  /** Global point coordinate in the CoreGraphics global space (top-left origin, Y grows down). */
  x: number
  y: number
}

/**
 * Press a single named key with optional modifiers. Useful for shortcuts
 * (Cmd+S, Ctrl+C), navigation (arrow keys), and special keys (Escape, F2).
 * For typing arbitrary text use `type_text` instead.
 */
export declare function pressKey(options: PressKeyOptions): void

export interface PressKeyOptions {
  /**
   * Either a named key (see README / KEY_NAMES) like "return", "escape",
   * "tab", "space", "left", "right", "up", "down", "f1".."f12", "home",
   * "end", "pageup", "pagedown", "delete", "backspace", "a".."z", "0".."9",
   * or a raw macOS virtual keycode passed as a stringified number ("36" =
   * kVK_Return). Letters / digits use kVK_ANSI_* and assume an ANSI/QWERTY
   * layout — for arbitrary text use `type_text` instead.
   */
  key: string
  modifiers?: ModifierFlags
}

/**
 * Type arbitrary text. Uses `CGEventKeyboardSetUnicodeString` so it works
 * with any Unicode (CJK, emoji, accented chars) regardless of the active
 * keyboard layout. Does NOT honor IME — the literal characters are
 * inserted into the focused input.
 */
export declare function typeText(options: TypeTextOptions): void

export interface TypeTextOptions {
  text: string
  /**
   * Per-character delay in milliseconds. Defaults to 0 (paste-like instant
   * typing). Some apps drop characters on rapid input — a small delay
   * (e.g. 5–15ms) helps.
   */
  perCharDelayMs?: number
}
